[package]
name = "chr-persistent"
version.workspace = true
edition.workspace = true

[features]
default = ["metrics"]
metrics = ["kernel-metrics", "chr-observe/metrics"]
kernel-metrics = []

[dependencies]
chr-syntax = { path = "../../crates/chr-syntax" }
chr-observe = { path = "../chr-observe", default-features = false }

[dev-dependencies]
chr-cases = { path = "../chr-cases" }
