[package]
name = "chr-integrated"
version.workspace = true
edition.workspace = true

[features]
default = ["metrics"]
metrics = ["chr-compiled?/metrics"]
experiment = ["dep:chr-compiled", "dep:chr-observe", "dep:chr-persistent"]
alloc-meter = ["experiment"]

[[bin]]
name = "chr-integrated-cost"
path = "experiments/native.rs"
required-features = ["experiment"]

[build-dependencies]
chr-syntax = { path = "../../crates/chr-syntax" }

[dependencies]
chr-persistent = { path = "../chr-persistent", default-features = false, optional = true }
chr-compiled = { path = "../chr-compiled", default-features = false, optional = true }
chr-observe = { path = "../chr-observe", optional = true }
chr-syntax = { path = "../../crates/chr-syntax" }

[dev-dependencies]
chr-observe = { path = "../chr-observe" }
