[package]
name="recursive-native-gate"
version="0.0.0"
edition="2024"
[workspace]
[dependencies]
chr-syntax={path="/home/ahart/Documents/CHRLang/crates/chr-syntax",default-features=false}
chr-persistent={path="/home/ahart/Documents/CHRLang/research/chr-persistent",default-features=false}
chr-observe={path="/home/ahart/Documents/CHRLang/research/chr-observe",default-features=false}
